added username for filters too
Signed-off-by: asubedy <frexpe@pm.me>

diff --git a/.github/workflows/add-catalog.yml b/.github/workflows/add-catalog.yml
--- a/.github/workflows/add-catalog.yml
+++ b/.github/workflows/add-catalog.yml
@@ -145,9 +145,25 @@ jobs:
             filterFile="$(jq -r .[$idx].filter_file temp.json)"
             echo "$filterFile" > $MESHERY_CATALOG_FILES_DIR/$filterId.yaml
 
+            userId=$(jq -r .[$idx].user_id temp.json)
+            userInfo=$(curl -sS "$MESHERY_CLOUD_BASE_URL/api/identity/users/profile/$userId" 2>./err1.txt)
+
+            if [[ "$(<err1.txt)" != "" ]]; then
+            >&2 echo "Error fetcheing User details"
+            >&2 echo "$(<err1.txt)"
+            fi
+
+            echo "$userInfo" > info.json
+
+            userFirstName=$(jq .first_name info.json)
+            userLastName=$(jq .last_name info.json)
+
+            userFullName=$(userFirstName) $(userLastName)
+
             echo "---
           layout: item
           name: $filterName
+          userName: $userFullName
           type: $filterType
           compatibility: $compatibility
           patternId: $(printf "FILTER%03d" $idx)
