fixed typo
Signed-off-by: asubedy <frexpe@pm.me>

diff --git a/.github/workflows/add-catalog.yml b/.github/workflows/add-catalog.yml
--- a/.github/workflows/add-catalog.yml
+++ b/.github/workflows/add-catalog.yml
@@ -67,7 +67,7 @@ jobs:
             userInfo=$(curl -sS "$MESHERY_CLOUD_BASE_URL/api/identity/users/profile/$userId" 2>./err1.txt)
 
             if [[ "$(<err1.txt)" != "" ]]; then
-            >&2 echo "Error fetcheing User details"
+            >&2 echo "Error fetching User details"
             >&2 echo "$(<err1.txt)"
             fi
 
@@ -149,7 +149,7 @@ jobs:
             userInfo=$(curl -sS "$MESHERY_CLOUD_BASE_URL/api/identity/users/profile/$userId" 2>./err1.txt)
 
             if [[ "$(<err1.txt)" != "" ]]; then
-            >&2 echo "Error fetcheing User details"
+            >&2 echo "Error fetching User details"
             >&2 echo "$(<err1.txt)"
             fi
 
